---
sidebar: sidebar 
permalink: scpivs44_unmount_a_backup.html 
keywords:  
summary: Una vez que ya no se necesita el acceso a los archivos del almacén de datos, es posible desmontar un backup. 
---
= Desmontar un backup
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Una vez que ya no se necesita el acceso a los archivos del almacén de datos, es posible desmontar un backup.

Si un backup se muestra como montado en la interfaz gráfica de usuario del cliente de VMware vSphere, pero no aparece en la pantalla de desmontaje de backup, deberá utilizar la API REST `/backup/{backup-Id}/cleanup` para limpiar los almacenes de datos no vinculados y, a continuación, volver a intentar el procedimiento de desmontaje.

Si se intenta montar una copia de backup de un almacén de datos NFS en una máquina virtual de almacenamiento (SVM) con el volumen raíz en una relación de reflejo de distribución de cargas y se puede encontrar el error `You may have reached the maximum number of NFS volumes configured in the vCenter. Check the vSphere Client for any error messages.` para evitar este problema, cambie la configuración de volúmenes máximos navegando a *ESX* > *Administrar* > *Ajustes* > *Avanzar Configuración del sistema* y cambiando NFS. Valor de MaxVolumes. El valor máximo es 256.

.Pasos
. En VMware vSphere Client, haga clic en *Menú* en la barra de herramientas y, a continuación, seleccione *Storage* en la lista desplegable.
. En el panel de navegación de la izquierda, haga clic con el botón derecho en un almacén de datos y seleccione *NetApp SnapCenter* en la lista desplegable; a continuación, seleccione Unmount en la lista desplegable secundaria.
+

IMPORTANT: Asegúrese de haber seleccionado el almacén de datos correcto para desmontar. De lo contrario, podría afectar al trabajo de producción.

. En el cuadro de diálogo *Unmount Cloned Datastore*, seleccione un almacén de datos, seleccione la casilla de verificación *Unmount the cloned datastore* y, a continuación, haga clic en *Unmount*.

